services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dymall
#      MYSQL_USER: your_user
#      MYSQL_PASSWORD: your_password

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nacos:
    image: nacos/nacos-server:v2.5.0
    container_name: nacos-standalone
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./standalone-logs/:/home/nacos/logs

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"


  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"     # allow a direct connection from container to the local machine
    ports:
      - "9090:9090"   # the default port used by Prometheus
    volumes:
      - ./grafana-k6/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"  # 关键参数
    networks:
      - grafana_net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000" # the default port used by Grafana
    networks:
      - grafana_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 关闭安全认证，开发环境下可用
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 限制内存使用
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # 管理界面
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass123




volumes:
  es_data:
    driver: local
  mysql_data:
    driver: local
  rabbitmq_data:

networks:
  grafana_net:
    driver:
      bridge

