dubbo:
  provider:
    delay: 3000
  protocol:
    name: dubbo
  application:
    #    qos-port: 22222
    logger: slf4j
    qos-port:
  registry:
    address: nacos://localhost:8848
    register-mode: instance

#spring:
#  elasticsearch:
#    uris: http://localhost:9200
#    username: jjr
#    password: 12345678


  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: pass123
