dubbo:
  provider:
    delay: 3000
  protocol:
    name: dubbo
  application:
    #    qos-port: 22222
    logger: slf4j
    qos-port:
  registry:
    address: nacos://localhost:8848
    register-mode: instance